In [1]:
from sqlalchemy import create_engine
import pandas as pd

In [2]:
engine  = create_engine("sqlite:///../input/soccer/database.sqlite")

In [3]:
def base_player_data():

  df_soccer_data = pd.read_sql("""
    select m.id as match_id, \
      m.country_id, \
      m.league_id, \
      m.season, \
      m.stage, \
      m.date as match_date, \
      m.home_team_api_id as home_team_id, \
      m.away_team_api_id as away_team_id, \
      m.home_team_goal, \
      m.away_team_goal, \
      m.goal, \
      m.shoton, \
      m.shotoff, \
      m.foulcommit, \
      m.card, \
      m.cross, \
      m.corner, \
      m.possession, \
      m.B365H, \
      m.B365D, \
      m.B365A, \
      m.BWH, \
      m.BWD, \
      m.BWA, \
      m.IWH, \
      m.IWD, \
      m.IWA, \
      m.LBH, \
      m.LBD, \
      m.LBA, \
      m.PSH, \
      m.PSD, \
      m.PSA, \
      m.WHH, \
      m.WHD, \
      m.WHA, \
      m.SJH, \
      m.SJD, \
      m.SJA, \
      m.VCH, \
      m.VCD, \
      m.VCA, \
      m.GBH, \
      m.GBD, \
      m.GBA, \
      m.BSH, \
      m.BSD, \
      m.BSA, \
      hta.buildUpPlaySpeed as home_buildUpPlaySpeed, \
      hta.buildUpPlaySpeedClass as home_buildUpPlaySpeedClass, \
      hta.buildUpPlayDribbling as home_buildUpPlayDribbling, \
      hta.buildUpPlayDribblingClass as home_buildUpPlayDribblingClass, \
      hta.buildUpPlayPassing as home_buildUpPlayPassing, \
      hta.buildUpPlayPassingClass as home_buildUpPlayPassingClass, \
      hta.buildUpPlayPositioningClass as home_buildUpPlayPositioningClass, \
      hta.chanceCreationPassing as home_chanceCreationPassing, \
      hta.chanceCreationPassingClass as home_chanceCreationPassingClass, \
      hta.chanceCreationCrossing as home_chanceCreationCrossing, \
      hta.chanceCreationCrossingClass as home_chanceCreationCrossingClass, \
      hta.chanceCreationShooting as home_chanceCreationShooting, \
      hta.chanceCreationShootingClass as home_chanceCreationShootingClass, \
      hta.chanceCreationPositioningClass as home_chanceCreationPositioningClass, \
      hta.defencePressure as home_defencePressure, \
      hta.defencePressureClass as home_defencePressureClass, \
      hta.defenceAggression as home_defenceAggression, \
      hta.defenceAggressionClass as home_defenceAggressionClass, \
      hta.defenceTeamWidth as home_defenceTeamWidth, \
      hta.defenceTeamWidthClass as home_defenceTeamWidthClass, \
      hta.defenceDefenderLineClass as home_defenceDefenderLineClass, \
      ata.buildUpPlaySpeed as away_buildUpPlaySpeed, \
      ata.buildUpPlaySpeedClass as away_buildUpPlaySpeedClass, \
      ata.buildUpPlayDribbling as away_buildUpPlayDribbling, \
      ata.buildUpPlayDribblingClass as away_buildUpPlayDribblingClass, \
      ata.buildUpPlayPassing as away_buildUpPlayPassing, \
      ata.buildUpPlayPassingClass as away_buildUpPlayPassingClass, \
      ata.buildUpPlayPositioningClass as away_buildUpPlayPositioningClass, \
      ata.chanceCreationPassing as away_chanceCreationPassing, \
      ata.chanceCreationPassingClass as away_chanceCreationPassingClass, \
      ata.chanceCreationCrossing as away_chanceCreationCrossing, \
      ata.chanceCreationCrossingClass as away_chanceCreationCrossingClass, \
      ata.chanceCreationShooting as away_chanceCreationShooting, \
      ata.chanceCreationShootingClass as away_chanceCreationShootingClass, \
      ata.chanceCreationPositioningClass as away_chanceCreationPositioningClass, \
      ata.defencePressure as away_defencePressure, \
      ata.defencePressureClass as away_defencePressureClass, \
      ata.defenceAggression as away_defenceAggression, \
      ata.defenceAggressionClass as away_defenceAggressionClass, \
      ata.defenceTeamWidth as away_defenceTeamWidth, \
      ata.defenceTeamWidthClass as away_defenceTeamWidthClass, \
      ata.defenceDefenderLineClass as away_defenceDefenderLineClass, \
      hp1.height as hp1_height, \
      hp2.height as hp2_height, \
      hp3.height as hp3_height, \
      hp4.height as hp4_height, \
      hp5.height as hp5_height, \
      hp6.height as hp6_height, \
      hp7.height as hp7_height, \
      hp8.height as hp8_height, \
      hp9.height as hp9_height, \
      hp10.height as hp10_height, \
      hp11.height as hp11_height, \
      ap1.height as ap1_height, \
      ap2.height as ap2_height, \
      ap3.height as ap3_height, \
      ap4.height as ap4_height, \
      ap5.height as ap5_height, \
      ap6.height as ap6_height, \
      ap7.height as ap7_height, \
      ap8.height as ap8_height, \
      ap9.height as ap9_height, \
      ap10.height as ap10_height, \
      ap11.height as ap11_height, \
      hp1.weight as hp1_weight, \
      hp2.weight as hp2_weight, \
      hp3.weight as hp3_weight, \
      hp4.weight as hp4_weight, \
      hp5.weight as hp5_weight, \
      hp6.weight as hp6_weight, \
      hp7.weight as hp7_weight, \
      hp8.weight as hp8_weight, \
      hp9.weight as hp9_weight, \
      hp10.weight as hp10_weight, \
      hp11.weight as hp11_weight, \
      ap1.weight as ap1_weight, \
      ap2.weight as ap2_weight, \
      ap3.weight as ap3_weight, \
      ap4.weight as ap4_weight, \
      ap5.weight as ap5_weight, \
      ap6.weight as ap6_weight, \
      ap7.weight as ap7_weight, \
      ap8.weight as ap8_weight, \
      ap9.weight as ap9_weight, \
      ap10.weight as ap10_weight, \
      ap11.weight as ap11_weight, \
      Julianday(m.date) - JulianDay(hp1.birthday) as hp1_age, \
      Julianday(m.date) - JulianDay(hp2.birthday) as hp2_age, \
      Julianday(m.date) - JulianDay(hp3.birthday) as hp3_age, \
      Julianday(m.date) - JulianDay(hp4.birthday) as hp4_age, \
      Julianday(m.date) - JulianDay(hp5.birthday) as hp5_age, \
      Julianday(m.date) - JulianDay(hp6.birthday) as hp6_age, \
      Julianday(m.date) - JulianDay(hp7.birthday) as hp7_age, \
      Julianday(m.date) - JulianDay(hp8.birthday) as hp8_age, \
      Julianday(m.date) - JulianDay(hp9.birthday) as hp9_age, \
      Julianday(m.date) - JulianDay(hp10.birthday) as hp10_age, \
      Julianday(m.date) - JulianDay(hp11.birthday) as hp11_age, \
      Julianday(m.date) - JulianDay(ap1.birthday) as ap1_age, \
      Julianday(m.date) - JulianDay(ap2.birthday) as ap2_age, \
      Julianday(m.date) - JulianDay(ap3.birthday) as ap3_age, \
      Julianday(m.date) - JulianDay(ap4.birthday) as ap4_age, \
      Julianday(m.date) - JulianDay(ap5.birthday) as ap5_age, \
      Julianday(m.date) - JulianDay(ap6.birthday) as ap6_age, \
      Julianday(m.date) - JulianDay(ap7.birthday) as ap7_age, \
      Julianday(m.date) - JulianDay(ap8.birthday) as ap8_age, \
      Julianday(m.date) - JulianDay(ap9.birthday) as ap9_age, \
      Julianday(m.date) - JulianDay(ap10.birthday) as ap10_age, \
      Julianday(m.date) - JulianDay(ap11.birthday) as ap11_age \
    from Match as m
      join Country as c
      on (c.id = m.country_id)
      join League as l
      on (l.id = m.league_id)
      join Team as ht
      on (m.home_team_api_id = ht.team_api_id)
      join Team as at
      on (m.home_team_api_id = at.team_api_id)
      join Team_Attributes as hta
      on (m.home_team_api_id = hta.team_api_id)
      join Team_Attributes as ata
      on (m.home_team_api_id = ata.team_api_id)
      left join player as hp1
      on (cast(m.home_player_1 as int) = hp1.player_api_id)
      left join player as hp2
      on (cast(m.home_player_2 as int) = hp2.player_api_id)
      left join player as hp3
      on (cast(m.home_player_3 as int) = hp3.player_api_id)
      left join player as hp4
      on (cast(m.home_player_4 as int) = hp4.player_api_id)
      left join player as hp5
      on (cast(m.home_player_5 as int) = hp5.player_api_id)
      left join player as hp6
      on (cast(m.home_player_6 as int) = hp6.player_api_id)
      left join player as hp7
      on (cast(m.home_player_7 as int) = hp7.player_api_id)
      left join player as hp8
      on (cast(m.home_player_8 as int) = hp8.player_api_id)
      left join player as hp9
      on (cast(m.home_player_9 as int) = hp9.player_api_id)
      left join player as hp10
      on (cast(m.home_player_10 as int) = hp10.player_api_id)
      left join player as hp11
      on (cast(m.home_player_11 as int) = hp11.player_api_id)
      left join player as ap1
      on (cast(m.away_player_1 as int) = ap1.player_api_id)
      left join player as ap2
      on (cast(m.away_player_2 as int) = ap2.player_api_id)
      left join player as ap3
      on (cast(m.away_player_3 as int) = ap3.player_api_id)
      left join player as ap4
      on (cast(m.away_player_4 as int) = ap4.player_api_id)
      left join player as ap5
      on (cast(m.away_player_5 as int) = ap5.player_api_id)
      left join player as ap6
      on (cast(m.away_player_6 as int) = ap6.player_api_id)
      left join player as ap7
      on (cast(m.away_player_7 as int) = ap7.player_api_id)
      left join player as ap8
      on (cast(m.away_player_8 as int) = ap8.player_api_id)
      left join player as ap9
      on (cast(m.away_player_9 as int) = ap9.player_api_id)
      left join player as ap10
      on (cast(m.away_player_10 as int) = ap10.player_api_id)
      left join player as ap11
      on (cast(m.away_player_11 as int) = ap11.player_api_id) """, engine)

  return df_soccer_data

In [4]:
data = base_player_data()
data.head()

,match_id,country_id,league_id,season,stage,match_date,home_team_id,away_team_id,home_team_goal,away_team_goal,...,ap2_age,ap3_age,ap4_age,ap5_age,ap6_age,ap7_age,ap8_age,ap9_age,ap10_age,ap11_age
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,9987,9993,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,1,2008/2009,1,2008-08-17 00:00:00,9987,9993,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1,1,2008/2009,1,2008-08-17 00:00:00,9987,9993,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,1,1,2008/2009,1,2008-08-17 00:00:00,9987,9993,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,1,1,2008/2009,1,2008-08-17 00:00:00,9987,9993,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN